name: Build and Publish

on:
  push:

jobs:
  build-and-push-docker-image:
    name: Build push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GL_USER }}
          token: ${{ secrets.GL_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.gitlab.com/abnerrizzi/my-scripts:latest
